# Generated by Django 5.0.7 on 2024-07-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact_info',
            new_name='contact_number',
        ),
    ]
