# Generated by Django 5.0.7 on 2024-07-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('PENDING', 'PENDING'), ('RESCHEDULED', 'RESCHEDULED'), ('CANCELLED', 'CANCELLED'), ('NO_SHOW', 'NO_SHOW'), ('COMPLETED', 'COMPLETED'), ('FOLLOWUP_NEEDED', 'FOLLOWUP_NEEDED')], max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
