# Generated by Django 5.0.7 on 2024-07-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
