# Generated by Django 5.0.7 on 2024-07-30 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ADMITTED', 'ADMITTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('STABILIZED', 'STABILIZED'), ('IMPROVED', 'IMPROVED'), ('TRANSFERRED', 'TRANSFERRED'), ('DISCHARGED', 'DISCHARGED')], max_length=255)),
                ('date_reported', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
